sustain/challenges/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'challenges'
urlpatterns = [
    path('', views.ChallengeView.as_view(), name='challenges'),
    path('delete_challenge/<int:pk>', views.ChallengeDeleteView.as_view(), name='delete_challenges'),
]

sustain/feed/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'feed'
urlpatterns = [
    path('', views.FeedView.as_view(), name='feed'),
    path('follow/<int:pk>', views.FollowView.as_view(), name='follow')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sustain/profiles/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = 'profiles'
urlpatterns = [
    path('', views.ProfileView.as_view(), name="profile"),
]

sustain/sustain/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    
    path('', include('users.urls', namespace='users')),
    path('feed/', include('feed.urls', namespace='feed')),
    path('challenges/', include('challenges.urls', namespace='challenges')),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('friends/', include('friends.urls', namespace='friends')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sustain/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

sustain/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    
    {% block title %}{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" rel="stylesheet" />
    {% block navbar %}{% endblock %}

        {% block style %}{% endblock %}
  </head>
  <body>
    {% block layout %}{% endblock %}
    {% block script %}{% endblock %}

    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">

    <!-- Core plugin JavaScript-->
    <script src="{% static 'jquery.easing.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'jquery.dataTables.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
    <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript"></script>
  </body>
</html>
<style>
  html, body {
    height: 100%;
    width: 100%;
    margin: 0;
    padding: 0;
    border: 0;
    background-color: #FFFFFF;
    overflow-x: hidden;
    padding-top: 50px;
  }
</style>

sustain/templates/base/layout.html
{% extends 'base/base.html' %}
{% load static %}
{% block navbar %}



<div class="container">
  <div class="profile-page tx-13">
    <nav class="navbar navbar-expand-lg bg-body-tertiary container sticky-top" id="NavbarContainer">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img src="{% static 'img/sustain_logo.png' %}" alt="Sustain Logo" height="60">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
          <ul class="navbar-nav">
            
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{%url 'feed:feed'%}">feed</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'challenges:challenges'%}">challenges</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profiles:profile' %}">profile</a>
            </li>
            <li class="nav-item">
              <a class="btn btn-success" href="{%url 'users:logout'%}">logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </container>
</div>
<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
<style>
  #NavbarContainer {
    background-color: #FFFFFF;
    border-bottom: 1px solid #ccc;
    width: 100%;
    position: fixed;
  }

  .nav-item {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  a {
    color: #28A745;
    font-size: 13pt;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .profile-picture {
    border-radius: 50%;
    width: 40px;  /* Set the width */
    height: 40px;  /* Set the height */
    object-fit: cover;  /* This will make sure the image covers the entire area */
  }

  .dropdown-item {
    width: 50%;
    height: 50%;
  }
</style>
  <script type="text/javascript"></script>
{% endblock %}
{% block style %}


{% endblock %}
{% block layout %}
    {% block body %}
    {% endblock %}
{% endblock %}
{% block script %}
{% endblock %}