sustain/challenges/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'challenges'
urlpatterns = [
    path('', views.ChallengeView.as_view(), name='challenges'),
    path('delete_challenge/<int:pk>', views.ChallengeDeleteView.as_view(), name='delete_challenges'),
]

sustain/feed/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'feed'
urlpatterns = [
    path('', views.FeedView.as_view(), name='feed'),
    path('follow/<int:pk>', views.FollowView.as_view(), name='follow')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sustain/sustain/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    
    path('', include('users.urls', namespace='users')),
    path('feed/', include('feed.urls', namespace='feed')),
    path('challenges/', include('challenges.urls', namespace='challenges')),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('friends/', include('friends.urls', namespace='friends')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sustain/challenges/models.py
from django.db import models
from users.models import Sustainer


class Challenge(models.Model):
    cause = models.CharField(
        max_length=100,
        null=True,
        blank=True,
    )
    description = models.CharField(
        max_length=1000,
        null=True,
        blank=True,
    )
    points = models.IntegerField(
        default=0,
        null=True,
        blank=True,
    )
    time = models.DateTimeField(
        null=True,
        blank=True,
    )
    latitude = models.FloatField(
        null=True,
        blank=True,
    )
    longitude = models.FloatField(
        null=True,
        blank=True,
    )
    completionStatus = models.BooleanField(
        default=False,
        null=True,
        blank=True,
    )
    sustainer = models.ForeignKey(
        to=Sustainer,
        on_delete=models.CASCADE,
    )
    image = models.ImageField(
        upload_to='challenge_images/',
        null=True,
        blank=True,
    )
    def __str__(self):
        return f"{self.cause}, {self.description}, {self.points}, {self.time}, {self.completionStatus}, {self.sustainer}"

sustain/challenges/views.py
from datetime import datetime

from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .models import Challenge
from keys.openAIKey import OPEN_AI_VAR
from django.core.files.storage import default_storage


# Create your views here.
class ChallengeView(TemplateView):
    template_name = 'challenges/challenges.html'
    
    def get(self, request):
        context = {'challenges' : Challenge.objects.filter(sustainer=request.user.sustainer, completionStatus=False)}
        return render(request, self.template_name, context)
    
    def post(self, request):
        if request.POST.get('location') == None or request.POST.get('location') == "Enter your location":
            support_cause = request.POST.get('support-dropdown')
            hours_to_help = request.POST.get('hours-dropdown')
            # Do something with the values
            import openai
            openai.api_key = OPEN_AI_VAR

            alignmentPrompt = """
            You are a 1-hour challenge generator for an app called 'sustain' to create a more happy and sustainable world.
            The challenges should be short and easy to complete.
            They should not include posting on social media, as the app requires you to post a picture of your completed challenge.
            You only give 1-2 sentence challenges in the following format:
            Hi User,
            Your challenge is: {insert_challenge_here}
            Go Forth and sustain!
            """

            time_limit = hours_to_help
            cause = support_cause
            UserPrompt = f"Create a challenge to help the following cause:{cause} with a time limit of ${time_limit}"

            response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": alignmentPrompt},
                    {"role": "user", "content": UserPrompt}
                ]
            )

            rawChallenge = response['choices'][0]['message']['content']
            try:
                parsedChallenge = rawChallenge.splitlines()[1].strip().split("is: ")[1]
            except:
                parsedChallenge = rawChallenge
            print(rawChallenge)
            print(parsedChallenge)
            print(response['usage'])
            
            new = Challenge(cause=cause, description=parsedChallenge, points=time_limit, sustainer=request.user.sustainer, time=datetime.now(), completionStatus=False)
            new.save()
            context = {
                'challenges': Challenge.objects.filter(sustainer=request.user.sustainer, completionStatus=False),
            }
            

            return render(request, self.template_name, context)
        else:
            import urllib.request
            import os
            curr_pk = request.POST.get('challenge_pk')
            print(curr_pk)
            print('test')
            challenge = Challenge.objects.get(id=curr_pk)
            challenge_location = request.POST.get('location')
            if 'picture' in request.FILES:
                challenge_picture = request.FILES['picture']
                folder_path = 'static/challenge_images'
                filename = f'{challenge.pk}.jpg'
                file_path = os.path.join(folder_path, filename)
                with open(file_path, 'wb+') as destination:
                    for chunk in challenge_picture.chunks():
                        destination.write(chunk)
                print(challenge_picture)
                challenge.image = challenge_picture  # Move this line here
            else:
                print("NO PICTURE")

            challenge.latitude = float(challenge_location.split(",")[0].strip())
            challenge.longitude = float(challenge_location.split(",")[1].strip())
            # challenge.image = challenge_picture
            challenge.time = datetime.now()
            challenge.completionStatus = True
            request.user.sustainer.challenges_completed += 1
            challenge.save()
            request.user.sustainer.save()
            return redirect('challenges:challenges')
        
    
    
class ChallengeDeleteView(TemplateView):
    
    def get(self, request, pk):
        challenge = Challenge.objects.get(id=pk)
        challenge.delete()
        return redirect('challenges:challenges')
        

sustain/templates/challenges/challenges.html
{% extends 'base/layout.html' %}
{% load static %}
{% block title %}
  <title>sustain | challenges</title>
{% endblock %}

{% block style %}
  {% for challenge in challenges %}
    <div class="card mb-3">
      <div class="row no-gutters">
        <div class="col-md-8">
          <div class="card-body">
            {% if challenge.cause == 'Mental_Health' %}
              <h5 class="card-title">Mental Health</h5>
            {% elif challenge.cause == 'green_spaces' %}
              <h5 class="card-title">Green Spaces</h5>
            {% elif challenge.cause == 'clean_air_water' %}
              <h5 class="card-title">Clean Air and Water</h5>
            {% elif challenge.cause == 'sustainable_transportation' %}
              <h5 class="card-title">Sustainable Transportation</h5>
            {% elif challenge.cause == 'climate_action' %}
              <h5 class="card-title">Climate Action</h5>
            {% elif challenge.cause == 'healthy_food_systems' %}
              <h5 class="card-title">Healthy Food Systems</h5>
            {% elif challenge.cause == 'energy_efficiency' %}
              <h5 class="card-title">Energy Efficiency</h5>
            {% elif challenge.cause == 'reduced_noise_pollution' %}
              <h5 class="card-title">Reduced Noise Pollution</h5>
            {% elif challenge.cause == 'waste_reduction' %}
              <h5 class="card-title">Waste Reduction</h5>
            {% elif challenge.cause == 'sustainable_housing' %}
              <h5 class="card-title">Sustainable Housing</h5>
            {% elif challenge.cause == 'community_engagement' %}
              <h5 class="card-title">Community Engagement</h5>
            {% else %}
              <h5 class="card-title">Cause: None</h5>
            {% endif %}

            <p class="card-text">{{challenge.description}}</p>
            <div class="align-items-bottom">
              <a href="#" class="btn btn-success" data-toggle="modal" data-target="#completeChallengeModal"><i class="fa-solid fa-check"></i> complete</a>
              <a href="{% url 'challenges:delete_challenges' challenge.pk %}" class="btn btn-primary" style="background-color: red;"><i class="fa-solid fa-trash-can"></i> delete</a>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="completeChallengeModal" tabindex="-1" role="dialog" aria-labelledby="completeChallengeModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-header">
                      <h5 class="modal-title" id="completeChallengeModalLabel">Complete Challenge</h5>
                      
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <div class="form-group">
                        <label for="profile-picture">Upload Challenge Picture</label>
                        <input type="file" class="form-control-file" id="challenge-picture" name="picture">
                      </div>
                      <div class="form-group">
                        <label for="location">Current Location</label>
                        <input type="text" class="form-control" name = "location" id="location" placeholder="Enter your location" readonly>
                        <button type="button" class="btn btn-primary" onclick="getLocation()">Get Current Location</button>
                        <input type="number" name="challenge_pk" value="{{ challenge.pk }}" hidden>
                      </div>

                      <script>
                        function getLocation() {
                          if (navigator.geolocation) {
                            navigator.geolocation.getCurrentPosition(showPosition);
                          } else {
                            alert("Geolocation is not supported by this browser.");
                          }
                        }

                        function showPosition(position) {
                          var latitude = position.coords.latitude;
                          var longitude = position.coords.longitude;
                          document.getElementById("location").value = latitude + ", " + longitude;
                        }
                      </script>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
            
          </div>
          
        </div>
        <div class="col-md-4">
          {% if challenge.cause == 'Mental_Health' %}
            <img src="{% static 'img/cause_mentalHealth.jpg' %}" class="card-img float-right" alt="..." height="258">
          {% elif challenge.cause == 'green_spaces' %}
            <img src="{% static 'img/cause_green_spaces.png' %}" class="card-img float-right" alt="..." height="258">
          {% elif challenge.cause == 'clean_air_water' %}
            <img src="{% static 'img/cause_clean_air_water.png' %}" class="card-img float-right" alt="..." height="258">
          {% elif challenge.cause == 'sustainable_transportation' %}
            <img src="{% static 'img/cause_sustainable_transportation.png' %}" class="card-img float-right" alt="..." height="258">
          {% elif challenge.cause == 'climate_action' %}
            <img src="{% static 'img/cause_climate_action.png' %}" class="card-img float-right" alt="..." height="258">
          {% elif challenge.cause == 'healthy_food_systems' %}
            <img src="{% static 'img/cause_healthy_food_systems.png' %}" class="card-img float-right" alt="..." height="258">
          {% elif challenge.cause == 'energy_efficiency' %}
            <img src="{% static 'img/cause_energy_efficiency.png' %}" class="card-img float-right" alt="..." height="258">
          {% elif challenge.cause == 'reduced_noise_pollution' %}
            <img src="{% static 'img/cause_reduce_noise_pollution.png' %}" class="card-img float-right" alt="..." height="258">
          {% elif challenge.cause == 'waste_reduction' %}
            <img src="{% static 'img/casue_waste_reduction.png' %}" class="card-img float-right" alt="..." height="258">
          {% elif challenge.cause == 'sustainable_housing' %}
            <img src="{% static 'img/cause_sustainable_housing.png' %}" class="card-img float-right" alt="..." height="258">
          {% elif challenge.cause == 'community_engagement' %}
            <img src="{% static 'img/cause_helping_the_needy.png' %}" class="card-img float-right" alt="..." height="258">
          {% else %}
            <img src="{% static 'img/cause_muscular_wood_guy.png' %}" class="card-img float-right" alt="..." height="258">
          {% endif %}
          
        </div>
      </div>
    </div>
  {% endfor %}

  <div class="text-center mt-4 mb-4">
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#createChallengeModal">Create Challenge</button>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="createChallengeModal" tabindex="-1" role="dialog" aria-labelledby="createChallengeModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form method="post">
        {% csrf_token %}
        <div class="modal-header">
          <h5 class="modal-title" id="createChallengeModalLabel">Create Challenge</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-1">
            </div>
            <div class="col-2">
              <label>Cause <label>
            </div>
            <div class="col-4">
              <select name="support-dropdown" id="support-dropdown">
                <option value="Mental_Health">Mental Health</option>
                <option value="green_spaces">Green Spaces</option>
                <option value="clean_air_water">Clean Air and Water</option>
                <option value="sustainable_transportation">Sustainable Transportation</option>
                <option value="climate_action">Climate Action</option>
                <option value="healthy_food_systems">Healthy Food Systems</option>
                <option value="energy_efficiency">Energy Efficiency</option>
                <option value="reduced_noise_pollution">Reduced Noise Pollution</option>
                <option value="waste_reduction">Waste Reduction</option>
                <option value="sustainable_housing">Sustainable Housing</option>
                <option value="community_engagement">Community Engagement</option>
              </select> 
            </div>
            </div>
            <div class="row">
              <div class="col-1">
              </div>
              <div class="col-2">
              <label>Time<label>
              </div>
              <div class="col-4">
              <select name="hours-dropdown" id="hours-dropdown">
                <option value="1">1 hour</option>
                <option value="2">2 hours</option>
                <option value="3">3 hours</option>
                <option value="4">4 hours</option>
                <option value="5">5 hours</option>
              </select> 
            </div>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Accept</button>
        </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}