sustain/feed/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'feed'
urlpatterns = [
    path('', views.FeedView.as_view(), name='feed'),
    path('follow/<int:pk>', views.FollowView.as_view(), name='follow')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sustain/friends/urls.py
from django.urls import path

from . import views

app_name = 'friends'
urlpatterns = [
    path('', views.FriendsView.as_view(), name='friends'),
]

sustain/sustain/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    
    path('', include('users.urls', namespace='users')),
    path('feed/', include('feed.urls', namespace='feed')),
    path('challenges/', include('challenges.urls', namespace='challenges')),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('friends/', include('friends.urls', namespace='friends')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sustain/friends/models.py
from django.db import models

# Create your models here.

sustain/friends/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from users.models import Sustainer


class FriendsView(TemplateView):
    template_name = 'friends/friends.html'

    def get(self, request):
        friends = request.user.sustainer.following.all()
        context = {'not_friends' : Sustainer.objects.all().exclude(following__in=friends)}
        return render(request, self.template_name, context)

sustain/templates/friends/friends.html
{% extends 'base/layout.html' %}

{% block title %}
  <title>sustain | people</title>
{% endblock %}


{% block body %}
<div class="card-body">
    <table class="table" id="dataTable" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Username</th>
                <th>Add Friend</th>
            </tr>
        </thead>
        <tbody>
            {% for friend in not_friends %}
                <tr>
                    <td>{{ friend.user.first_name }}</td>
                    <td>{{ friend.user.username }}</td>
                    <td><a class="btn btn-icon" href="{% url 'feed:follow' friend.pk %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user-plus" data-toggle="tooltip" title data-original-title="Connect">
                          <path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                          <circle cx="8.5" cy="7" r="4"></circle>
                          <line x1="20" y1="8" x2="20" y2="14"></line>
                          <line x1="23" y1="11" x2="17" y2="11"></line>
                        </svg>
                      </a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}